create database data_analysis_project
select * from customer_behaviour_analysis

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Business Insights Questions
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- 1. Which category generates highest revenue?
select category, 
round(sum(purchase_amount),2) as highest_revenue
from customer_behaviour_analysis
group by category
order by highest_revenue desc

-- ? Business Problem :- Company does not know which category contributes most to revenue.
-- Impact :-
--                   Helps prioritize high-performing categories
--                   Optimizes inventory planning
--                   Improves marketing ROI

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Are discounts actually increasing purchase value?  (discount dene se hamko fayeda ho rha hai ya phir nuksan ho rha hai)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
select * from customer_behaviour_analysis
select discount_applied,
round(sum(purchase_amount),2) as Total_revenue
from customer_behaviour_analysis
group by discount_applied

-- ? Business Problem :- Discounts may reduce profit without increasing sales.
-- Impact :-
--           Identify effectiveness of discounts
--             Reduce unnecessary discount costs
--                Improve profit margins|
------------------------------------------------------------------------------------------------------------
-- 3. What is the total revenue generated by male and female customer ?
------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select gender,
round(sum(purchase_amount),2) as Total_revenue
from customer_behaviour_analysis
group by gender
order by Total_revenue DESC

-- ? Business Problem :- Lack of understanding of revenue contribution by gender segments.
-- Impact :-
-- Helps design targeted marketing campaigns
-- Improves customer segmentation strategy
-- Enhances personalization efforts

--------------------------------------------------------------------------------------------------------
-- 4. Which customer used a discount but still spent more then the average purchase amount ?
--------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select customer_id, purchase_amount, discount_applied
from customer_behaviour_analysis
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount)from customer_behaviour_analysis)
order by purchase_amount limit 10 

-- ? Business Problem :- Company cannot identify high-spending customers who are also discount users.
-- Impact :-
-- Identifies premium discount-sensitive customers
-- Enables targeted discount campaigns
-- Improves customer retention and revenue

------------------------------------------------------------------------------------------------------------------------
-- 5. Which are the top/bottom 5 products with the highest average review rating.
------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select item_purchased,
round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings DESC limit 5 

-- ? Business Problem :- No visibility into product performance based on customer satisfaction.
-- Impact :-
-- Promotes high-performing products
-- Improves low-rated products
-- Enhances customer experience

---------------------------------------------------------------------------------------------------------------------------------------
-- 6. Average purchase: Standard vs Express shipping
---------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select shipping_type,
count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase
from customer_behaviour_analysis
where shipping_type in ('Standard','Express')
group by shipping_type 
-- ? Business Problem :- Unclear if faster shipping leads to higher spending.
-- Impact
-- Helps optimize shipping pricing strategy
-- Encourages premium shipping adoption
-- Increases average order value

----------------------------------------------------------------------------------------------------------------------------------------
-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
----------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select subscription_status,
count(customer_id) as users,
round(avg(purchase_amount),2) as avg_revenue,
round(sum(purchase_amount),2) as total_revenue
FROM customer_behaviour_analysis
group by subscription_status
order by total_revenue desc

-- ? Business Problem :- The effectiveness of subscription programs is unknown.
-- Impact
-- Validates subscription model performance
-- Improves customer loyalty programs
-- Increases customer lifetime value (CLV)

---------------------------------------------------------------------------------------------------------------------------------------
-- 8. Top 5 products with highest discount usage %
---------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis
select item_purchased,
count(item_purchased) as total_time_sold,
count(case when discount_applied = 'Yes' then 1 end ) as number_of_time_sold_when_discount_is_applied,
round(count(case when discount_applied = 'Yes' then 1 end ) * 100.0 / count(*) ,2) as discount_persentage
FROM customer_behaviour_analysis
group by item_purchased 
order by discount_persentage desc limit 5

-- ? Business Problem :- Some products may be overly dependent on discounts.
-- Impact :-
-- Identifies discount-driven products
-- Helps optimize pricing strategy
-- Reduces profit margin loss

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase,
-- and show the count of each segment.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis

select case
when previous_purchases = '0' then 'New Customer'
when previous_purchases between 1 and 15 then 'returning Customer'
else 'Loyal Customer' end as customer_segment,
count(*) customer_count
FROM customer_behaviour_analysis
group by case
when previous_purchases = '0' then 'New Customer'
when previous_purchases between 1 and 15 then 'returning Customer'
else 'Loyal Customer' end
;
-- ? Business Problem :- Lack of customer segmentation leads to generic strategies.
-- Impact :-
-- Enables personalized marketing
-- Improves retention strategies
-- Increases conversion rates
----------------------------------------------------------------------------------------------------------------------------------
-- 10. What are the top 3 most purchased products within each category ?
----------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis;

with cte as (
select category,item_purchased,
count(item_purchased) as most_purchased,
rank() over(partition by category order by count(item_purchased) desc) as RNK
from customer_behaviour_analysis
group by category,item_purchased)
select * from cte
where RNK <=3 ;

-- ? Business Problem :- The company doesn't know top-performing products within categories.
-- Impact
-- Improves product placement & recommendations
-- Helps inventory optimization
-- Increases sales through best-sellers

----------------------------------------------------------------------------------------------------------------------------------
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
----------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis;

SELECT
CASE
WHEN previous_purchases > 5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
END AS customer_type,
subscription_status,
COUNT(*) AS customer_count,
COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE
WHEN previous_purchases > 5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
end
) AS percents
FROM customer_behaviour_analysis
GROUP BY CASE
WHEN previous_purchases > 5 THEN 'Repeat Buyers'
ELSE 'Normal Buyers'
END, subscription_status;

-- ? Business Problem :- Unclear relationship between loyalty and subscription.
-- Impact :-
-- Improves subscription targeting
-- Increases conversion to paid programs
-- increase customer retention strategy I


----------------------------------------------------------------------------------------------------------------------------------
-- 12. What is the revenue contribution of each age group ?
----------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM customer_behaviour_analysis;
select case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '50+' end as age_group,
round(sum(purchase_amount),2) as Total_revenue
FROM customer_behaviour_analysis
group by case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '50+' end
order by Total_revenue desc

-- ? Business Problem :- No visibility into which age group contributes most to revenue.
-- Impact :-
-- Enables age-based targeting
-- Enhances marketing efficiency